name: neptune
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  bloc: ^8.1.2
  build_runner: ^2.4.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_custom_dialog: ^1.3.0
  flutter_exit_app: ^1.1.2
  flutter_inset_box_shadow: ^1.0.8
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  just_audio: ^0.9.36
  pro_animated_blur: ^0.0.2+1
  provider: ^6.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  shimmer_animation: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/titles/
    - assets/bg/
    - assets/cards/
    - assets/difficulty/
    - assets/music.mp3
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
